version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
  publisher:
    build:
      context: ./publisher
    ports:
      - '8000:8000'
    container_name: publisher
    depends_on:
      redis:
        condition: service_healthy
    volumes:
       - ./publisher:/src/
  subscriber:
    build:
      context: ./subscriber
    ports:
      - '9000:9000'
    container_name: subscriber
    depends_on:
      redis:
        condition: service_healthy
    volumes:
       - ./subscriber:/src/
  webapp:
    build:
      context: ./webapp
    ports:
      - '3000:3000'
    container_name: webapp
    volumes:
       - ./webapp:/src/